### ISSUE TITLE
heu

### ISSUE THREAD

**Issue by jb255** [viko42/stargazer-test#1]
c'ést pas un peu rasiste tout ca ?

**Comment by jb255** [comment]
https://img.radio-canada.ca/2013/04/11/635x357/130411_8q7ea_sebida-reconstitution_sn635.jpg

**Comment by jb255** [comment]
![raciste ton programme](https://user-images.githubusercontent.com/16245781/33036767-b4baa11c-ce2f-11e7-9dfb-de3498a3f25f.jpg)

**Comment by viko42** [comment]
Ça va être compliqué à fix ça Jb !
